import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/Backgound/Background";
import { LanguageProvider } from "@/widgets/header/UseTrnaslation";
import { orbitron } from '@/widgets/utils/fonts';

export const metadata: Metadata = {
  title: "1TRACE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={orbitron.variable}>
        <LanguageProvider>
            <Background />
            {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
